WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 1000

MAX_IMAGE_SIZE = 1000
DISPLAY_CANVAS_SIZE = 300

HISTOGRAM_BINS = 256
HISTOGRAM_RANGE = (0, 256)

COLOR_GRAYSCALE = "grayscale"
COLOR_RGB = "rgb"

METHOD_SPESIFIKASI = "spesifikasi"
METHOD_EQUALIZATION = "equalization"

CHART_LINE = "line"
CHART_BAR = "bar"

COLOR_BG = '#f0f0f0'
COLOR_WHITE = 'white'
COLOR_WARNING = 'red'
COLOR_SUCCESS = 'green'
COLOR_BTN_Primary = '#FF9800'
COLOR_BTN_SUCCESS = '#4CAF50'
COLOR_BTN_INFO = '#2196F3'
COLOR_BTN_DANGER = '#f44336'
COLOR_BTN_SECONDARY = '#9C27B0'
